dist: trusty
sudo: required

language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

addons:
  apt:
    packages:

before_script:
  - composer install

script:
  - "vendor/bin/phpunit --configuration phpunit.xml --coverage-text"